### PR TITLE
Fix various translation errors

### PR DESCRIPTION
**Pull request by llewelld**
Thanks to spodermenpls for spotting them.

### CODE REVIEW

**Comment by llewelld** [comment]
@spodermenpls: does this look okay for addressing the issues you noticed in your comment to #46?

**Comment by spodermenpls** [comment]
@llewelld Mostly yes, my eagle eyes spotted some new errors, though:

```
<translation type="unfinished">Unbekannter Fehler</translation>
<translation type="unfinished">Ungültiger Eintrag, bitte überprüfen Sie diesen.</translation>
<translation type="unfinished">Ungültige TAN, bitte überprüfen Sie diese.</translation>

<translation type="unfinished">无效项目。请核对你的项目。</translation>
<translation type="unfinished">TAN 码无效，请核对你的项目。</translation>
<translation type="unfinished">未知错误</translation>
```
Those look pretty finished to me, ` type="unfinished"` slipped probably back in due to copy-paste action to correct the typos in their source strings. If it would be up to me, I'd brush them under the rug and not archive them in a "oldsource" tag, but maybe there's some deeper meaning to it that flew past me. 😄

Edit: I've already injected my nickname in the German "contributor" translation string, one time is enough. 😅
`<translation>ApostolosB, dashinfantry, flypig, smdesai, spodermenpls, spodermenpls, Thaodan</translation>`

**Comment by llewelld** [comment]
Thanks again for your eagle eyes. I think I tidied everything up and it certainly looks better to me now; does it look okay to you?

**Comment by spodermenpls** [comment]
Yes, that's sufficient. My remark about the "oldsource" tags only revolved around the 3 typo lines, but to abstain from "oldsource" strings as a whole, like you did now, obviously unclutters the templates. and may reduce confusion for translators a bit too. I never seen those additional strings in use before (may be due to the fact that the locale projects I maintained before weren't related to C++ and Sailfish), but changes over the course of time are easily fetchable through Github's "history" feature, so there's probably not a real need for it.

**Comment by llewelld** [comment]
As far as I'm aware the `oldstring`s aren't used by the app, so it did just seem cleaner to remove them all. Thanks again for all your help with this.

I'll push an update today that's likely to introduce some new strings (I have to add a "warning" about using the official servers). If you're able to take a look at them, I'd be really grateful.

**Pull request merged**
