### PR TITLE
Support automatic update of diagnosis keys

### PR DESCRIPTION
**Pull request by llewelld**
Currently the user has to manually update the diagnosis keys from the server each day.

This change adds the ability to set the app to perform an automatic update at a specified time each day.

### CODE REVIEW

**Comment by llewelld** [comment]
Fixes #78.

**Comment by llewelld** [comment]
Rebased.

**Review by bionade24 — APPROVED** [review]

**Comment by bionade24** [comment]
Is keepalive `libkeepalive` ? If so, how does it have anything to do with TCP connections then?

**Comment by llewelld** [comment]
> Is keepalive `libkeepalive` ? If so, how does it have anything to do with TCP connections then?

A good question. This is [nemo-keepalive](https://git.sailfishos.org/mer-core/nemo-keepalive) for performing background processing, rather than [the libkeepalive](http://libkeepalive.sourceforge.net/) for maintaining long-lived TCP connections.

**Comment by bionade24** [comment]
> > Is keepalive `libkeepalive` ? If so, how does it have anything to do with TCP connections then?
> 
> A good question. This is [nemo-keepalive](https://git.sailfishos.org/mer-core/nemo-keepalive) for performing background processing, rather than [the libkeepalive](http://libkeepalive.sourceforge.net/) for maintaining long-lived TCP connections.

Thanks couldn't find the correct git repo of it. 
And the `libkeepalive` packages in the SFOS repo are from `nemo-keepalive`, aren't they?

**Comment by llewelld** [comment]
> And the `libkeepalive` packages in the SFOS repo are from `nemo-keepalive`, aren't they?

They are, yes; see here, and especially the description at the end:
```bash
[mersdk@c2881f6c7db8 ~]$ sb2 pkg-config --cflags keepalive
-I/usr/include/keepalive -I/usr/include/qt5/QtDBus -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/include/qt5
[mersdk@c2881f6c7db8 ~]$ sb2 rpm -q --whatprovides /usr/include/keepalive
libkeepalive-devel-1.8.4-1.4.10.jolla.armv7hl
[mersdk@c2881f6c7db8 ~]$ zypper info libkeepalive-devel

Information for package libkeepalive-devel:
-------------------------------------------
Repository     : oss                                 
Name           : libkeepalive-devel                  
Version        : 1.8.3-1.3.35.jolla                  
Arch           : i486                                
Vendor         : meego                               
Installed Size : 5.5 KiB                             
Installed      : No                                  
Status         : not installed                       
Source package : libkeepalive-1.8.3-1.3.35.jolla.src 
Summary        : Development headers for libkeepalive
Description    :                                     
    Development package for CPU and display keepalive and scheduling library

[mersdk@c2881f6c7db8 ~]$ 

```
I'm not sure what you're supposed to do if you want to use the other one, if I'm honest.

**Comment by bionade24** [comment]
I wish zypper would provide a URL to the upstream project like `apt` or `pacman` are doing it.

**Comment by llewelld** [comment]
> I wish zypper would provide a URL to the upstream project like `apt` or `pacman` are doing it.

It would be helpful I agree. I can't see a way to do it with zypper, and I'm not even sure all the sailfish spec files contain the correct URL, but you can at least persuade package kit to relinquish the info if it exists:
```bash
[nemo@Columba contrac]$ pkcon get-details libkeepalive
Package description
  package:     libkeepalive-1.8.4-1.4.24.jolla.armv7hl
  summary:     CPU and display keepalive and scheduling library
  license:     LGPLv2
  group:       unknown
  description: CPU and display keepalive and scheduling library
  size:        45960 bytes
  url:         https://git.sailfishos.org/mer-core/nemo-keepalive/
```

**Pull request merged**
