### PR TITLE
Download by day; support different download regions

### PR DESCRIPTION
**Pull request by llewelld**
The servers provide diagnosis key downloads in blocks of either hours or
days. Previously, the hourly files were downloaded, but on some recent
dates the hourly files have been missing, while the day files have still
been available.

This changes the download code to collect the day files rather than the
hour files.

In addition it also allows the region prefix to be changed, currently
between Germnay (DE) and Europe (EUR).

### CODE REVIEW

**Comment by llewelld** [comment]
Fixes #76 and #82.

**Comment by bionade24** [comment]
Is there anything I can do to get this merged faster?

**Review by bionade24 — APPROVED** [review]

**Comment by llewelld** [comment]
> Is there anything I can do to get this merged faster?

Thanks for the approval, that's the best way right now. More generally, if you're interested in becoming a "maintainer" with merge rights, then we should discuss that.

**Comment by bionade24** [comment]
> > Is there anything I can do to get this merged faster?
> 
> Thanks for the approval, that's the best way right now. More generally, if you're interested in becoming a "maintainer" with merge rights, then we should discuss that.

Would be nice, I only approved the parts I was sure they're right. But before I need some local test setup get working. I just want to help, not immedeately maintain it.

**Comment by llewelld** [comment]
Okay, let's discuss this separately, I suggest we get your GUID contribution merged first, but I can say that your help would be (already is) really appreciated. I'll try to get a test server running this week that we can both access and will let you know how I get on. Feel free to ping me on IRC (freenode, #sailfishos channel, as flypig) as another way to discuss all this.

**Pull request merged**
