### PR TITLE
Settings housekeeping

### PR DESCRIPTION
**Pull request by llewelld**

### CODE REVIEW

**Comment by llewelld** [comment]
Rebased.

**Comment by llewelld** [comment]
I proposed these changes because I noticed my phone going through the battery faster than usual, and the setting file being updated frequently and thought they might be related.

The battery depletion turned out to be something else. Nevertheless, it probably still makes sense to only save out the settings file in case something has actually changed.

**Review by bionade24 — APPROVED** [review]
`force` could have been optional but nevermind.

**Comment by llewelld** [comment]
> `force` could have been optional but nevermind.

This was added to cover the case where the file is changed by a different process. In this case, I thought it would be prudent to force the saving of the file on shutdown.

Are you thinking I could repurpose `m_dirty` to do the same?

**Comment by bionade24** [comment]
> > `force` could have been optional but nevermind.
> 
> This was added to cover the case where the file is changed by a different process. In this case, I thought it would be prudent to force the saving of the file on shutdown.
> 
> Are you thinking I could repurpose `m_dirty` to do the same?

I ment `void Settings::writeSettingsToDisk(bool force = true)`. Otherwise `writeSettingsToDisk(bool const   &force)` would be enough. Just a idea, not a must-have. It's good as it is.

**Comment by llewelld** [comment]
> I ment `void Settings::writeSettingsToDisk(bool force = true)`. Otherwise `writeSettingsToDisk(bool const &force)` would be enough. Just a idea, not a must-have. It's good as it is.

Thanks; this is a good idea.

I accidentally messed up my commits early and the majority of this merge got sucked into master by mistake. So, this PR is now specifically making the fix you suggested instead.

**Pull request merged**
